# BY ZF: virtualPlug backend config.
mqtt_host=192.168.10.126
mqtt_port=1883
mqtt_keepalive=60
mqtt_client_id=virtual_plug
mqtt_topic_prefix=tcu
http_host=127.0.0.1
http_port=18080
bias_no=0
gun_count=2
