;版本2.0
;对多个块进行简单整理
;最新支持江宁公交二期
;分时电价时间精确到分钟
;版本1.03
;说明:1、充放电单电表或双电表计量选择（单电表需设置地址、双电接两个485口）
;2、增加反向电量计量选择（只问正向、只问反向、正反都问）

;版本1.02
;说明:增加充放电选择

[电价]
是否分时=1
单一电价=1

峰=0.917000
谷=0.317000
尖=1.066000
平=0.586000

;直流电表、单相直接式电表、三相直接式电表设置为1
;三相经CT接入的电表根据实际变比设置
;如CT变比为75/5,则此处设置为15
变比=1

;南网贵州配置计费电表
;直流桩：0为直流表，1为交流表
;交流桩：此项无效
电表选择=0

;电表地址 6个字节  12位数字 由高到低
;电表地址目前只接受数字
;与充放电双电表共用，当充放电版本=2时，直流充电、交流放电
直流电表=111111111111
交流电表=222222222222

;电表地址 6个字节  12位数字 由高到低
;电表地址目前只接受数字
;江宁公交双电表计费版本
左侧电表=000000000012
右侧电表=000000000193

[放电]
单一电价放=0.00
峰放=1.4
谷放=0.8
尖放=2.0
平放=1.0

[充电桩]
交流=0
三相=0
在线=0
1491调试=0
贵州图标=0
;支持扫码及刷卡
远程启动=1
;对于启动刷卡时锁卡标志的判断，不影响结算刷卡解灰
灰锁判断=0
;用于VIN在线鉴权
车辆在线鉴权=0
;是否开放刷卡 0为开放 1为关闭
刷卡使能=0

[互动化平台]
;主站IP=192.168.8.133
主站IP=192.168.2.88
;主站端口=2409
主站端口=2409
;集中器地址=1
集中器地址=11041
桩地址=6
CAN地址=6
桩序列号=fgqo2VlvjqOu0dEUnSjIeECTFJnwMLvvGhDFX9mSGHnbZWlihQyPFWh5uUkzb8fi
[日志]
格式=[%time] %log
存盘文件=cui.log
存盘=0
显示=1

[早期日志]
CAN通信报文使能=0
电表通信报文使能=0
读卡器通信报文使能=0

充电逻辑日志使能=1
CAN通信逻辑日志使能=0
电表通信逻辑日志使能=0
读卡器通信逻辑日志使能=0

[协议版本]
;协议版本1.03为0  1.10为1 2为1.20
与桩控制器协议版本=1
桩控协议=1
;电表协议0为645,1为698
电表协议版本=0
;用于显示cui的版本，防止cui被清零
配置版本=1.04
;工厂调试 用于输入显示
调试显示输入=0
;江宁双电表自加
双电表自加=0
;分时电价测试
分时电价测试=0
;需求电压电流显示
需求显示=0
;针对不同厂家充电桩控制器对电流的处理不一致
绝对值=1

[计费程序版本]
;江宁公交版本双电表计费
江宁公交版本=0
;充放电版本选择
;0为充电桩
;1为充放电桩；单电表模式
;2为充放电桩：双电表模式，充放电各一块表
充放电版本=0
;此版本为双电表计费，同时需要设置江宁公交版本
充电弓版本=0
;允许设置需求信息下发
设置需求电压电流=0
;是否允许液晶启停
液晶启停=0
;VIN鉴权，同时读取VIN库
车架号鉴权=0
;读卡器流程精简 0:为完整流程  1:去除灰锁处理  2:去除灰锁处理和余额处理  
读卡器=0
;选择鉴权模式，需配合条件编译
选择鉴权=1
;基于选择鉴权方式，远程启动后如何停机 1、输入6位密码 
停机方式=0
;充电金额显示 0:正常显示 1:桩端不计费 2:短横
金额显示=0
电缆判断=0

[分时时段设置]
;尖峰平谷分时以时为单位
;每个时段提供四个时段
;第一个字节为开始时间，第二个字节为结束时间
;请从一到四按顺序填写
;默认峰时段为早8点至12点，下午17点至21点
;默认平时段为午12点至17点，晚上21点至24点
;默认谷时段为凌晨0点至8点
;默认尖时段暂无

分时测试=0

尖时段一使能=1
尖时段一=14001500

尖时段二使能=1
尖时段二=19302130

尖时段三使能=0
尖时段三=00000000

尖时段四使能=0
尖时段四=00000000

峰时段一使能=1
峰时段一=15001930

峰时段二使能=1
峰时段二=21302200

峰时段三使能=0
峰时段三=00000000

峰时段四使能=0
峰时段四=00000000

平时段一使能=1
平时段一=06001100

平时段二使能=1
平时段二=13001400

平时段三使能=1
平时段三=22000000

平时段四使能=0
平时段四=00000000

谷时段一使能=1
谷时段一=00000600

谷时段二使能=1
谷时段二=11001300

谷时段三使能=0
谷时段三=00000000

谷时段四使能=0
谷时段四=00000000




[主站遥控]
检修一=0
