#monitor.ini 20240425
IP=127.0.0.1
PORT=8801
ADDR=257
#Starting sequence environment Settings
SEQUENCE=TCU,CCU,HMI
#Charge Control Unit 
CCU=ccu_main
CCU_PATH=/opt/app/ccu/
CCU_CHECK=enable
CCU_FAULT_HANDING=1
CCU_HEARTBEAT_CHECK=0
CCU_UDP_IP=127.0.0.1
CCU_UDP_PORT=8802
CCU_UDP_FRAMEADDR=513
CCU_BLOCKING_TIME=1000
#Human-machine interface environment Settings
#HMI=hmi_main
#HMI_PATH=/opt/app/hmi/
#HMI_CHECK=enable
#HMI_FAULT_HANDING=0
#HMI_HEARTBEAT_CHECK=0
#HMI_UDP_IP=127.0.0.1
#HMI_UDP_PORT=8805
#HMI_UDP_FRAMEADDR=1281
#HMI_BLOCKING_TIME=1000
##
#TCU=nr_main
#TCU_PATH=/opt/app/tcu/
#TCU_CHECK=enable
#TCU_FAULT_HANDING=0
#TCU_HEARTBEAT_CHECK=0
#TCU_UDP_IP=127.0.0.1
#TCU_UDP_PORT=8803
#TCU_UDP_FRAMEADDR=769
#TCU_BLOCKING_TIME=1000
#
