# SHM2CCU 主控通信进程配置文件
# BY ZF
#
# 说明：
# 1. 当前 SHM2CCU 仅支持共享内存通信
# 2. 枪口遥信/遥测点位按左枪基准点号读取，右枪自动按 +256 偏移
# 3. 当前默认共享内存 key 为 85000
# 4. 进程入口默认读取 /usr/app/config/pile_controller.ini

[PileController]
# 充电枪数量
gun_count=2

# 全局参数
packet_timeout=3
retry_count=3

# MQTT 配置
mqtt_host=192.168.2.88
mqtt_port=1883
mqtt_keepalive=60
mqtt_client_id=shm2ccu_5
mqtt_topic_prefix=tcu
bias_no=8
# ========== 左枪 ==========
gun1_comm_type=shm
gun1_protocol_type=shm2ccu
gun1_shm_key=85000

# ========== 右枪 ==========
gun2_comm_type=shm
gun2_protocol_type=shm2ccu
gun2_shm_key=85000
