[ChargeLogic]
# MQTT
mqtt_host=192.168.1.200
mqtt_port=1883
mqtt_keepalive=60
mqtt_client_id=tcu_logic
mqtt_topic_prefix=tcu

# gun count (fallback). If pile_config_path is set, will read PileController.gun_count
# gun_count=1
pile_config_path=/usr/app/config/pile_controller.ini
