[配置版本]
;增加遥控信息等
;配置版本=1.06
;对配置进行分类，增新功能
配置版本=2.01

[电价]
是否分时=1
单一电价=1

峰=1.04500
谷=0.87100
尖=1.27300
平=0.00000

;直流电表、单相直接式电表、三相直接式电表设置为1
;三相经CT接入的电表根据实际变比设置
;如CT变比为75/5,则此处设置为15
变比=1

;电表地址 6个字节  12位数字 由高到低
左侧电表=523001000001
右侧电表=523001000002


;桩控通信 0 udp 1 can
[充电桩]
交流=0
在线=1
贵州图标=0
远程启动=1
二维码使能=1
运营项目=0
桩控通信=1
申请计费模型=1
车辆在线鉴权=1
中德平台=0


[互动化平台]
;153.99.84.178
主站IP=39.100.66.103
主站端口=2409
;13、14、15
集中器地址=1243
桩地址=1
私钥=0102030405060708090A0B0C0D0E0F10
桩序列号一=3201132023122124660074126
桩序列号二=11111111

[日志]
格式=[%time] %log
存盘文件=cui.log
存盘=0
显示=1

[早期日志]
CAN通信报文使能=0
电表通信报文使能=1
读卡器通信报文使能=0

充电逻辑日志使能=1
CAN通信逻辑日志使能=0
电表通信逻辑日志使能=1
读卡器通信逻辑日志使能=0

udp转can通信逻辑日志使能=0

[功能选择]
;强制合并充电
强制合并充电=0
;用于分时电价测试，电量会自动增长
分时电价测试=0
;刷卡启动时是否判断卡上余额
判断卡余额=0
;刷卡启动时是否判断卡灰锁，对外运营需使用
判断卡灰锁=0
;判断卡的前四位号段
判断卡号段=0
;1为显示两处含充电中界面，2为只在设备信息中显示，3为正常显示
显示车辆需求=3
;由于充电网C2000不支持断电保持，按用户需求通过断电后通信故障来判断是否保存充电记录
是否使用桩通信存记录=0
;逻辑主函数打印信息
打印信息=0
;充电端口编号 0为01,1为12
充电端口=1
;统一设计桩号 0为F6，1为E0/E1 需与充电端口配合使用
充电桩号=1
;读卡器流程精简 0:为完整流程  1:去除灰锁处理  2:去除灰锁处理和余额处理
读卡器=0
;停止充电按钮 目前使用在车辆在线鉴权中
停止按钮=1
;对VIN、自编号启动进行使能
车辆识别=1
车自编号=1
;基于选择鉴权方式，远程启动后如何停机 1、输入6位密码 
停机方式=0
;充电金额显示 0:正常显示 1:桩端不计费 2:短横
金额显示=0
[计费程序版本]
;充放电功能
;5双枪，每枪一个电表，允许合并放电
充放电版本=5

[协议版本]
;VIN鉴权，同时读取VIN库 模式一:自动VIN     模式二:选择充电模式(不含VIN)   
;模式三:选择充电模式(含VIN) 模?剿?选择充电模式(含1.2国网统一设计的VIN) 
;模式十：只支持刷卡合并充电，不支持单枪充电
车架号鉴权=2
;协议版本 0为1.10 1为1.03 2为1.20
桩控协议=2


